name: Pulumi - CI

on:
  push:
    branches:
      - main

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            id: checkout
            uses: actions/checkout@v4

          - name: Set up Node.js
            id: install-node
            uses: actions/setup-node@v4
            with:
              node-version-file: package.json

          - name: Install PNPM
            id: install-pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 8

          - name: Install dependencies
            id: install-dependencies
            run: pnpm install

          - name: Configure AWS credentials
            id: configure-aws-credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Run Pulumi
            id: run-pulumi
            uses: pulumi/actions@v6
            with:
              command: up
              stack-name: rocketseat.iac/stg
              cloud-url: s3://pulumi-state-migotto-360
            env:
              AWS_ACESS_KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ${{ secrets.AWS_REGION }}
